// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_delta_elite_assault_aa";
	a[1] = "body_delta_elite_assault_ab";
	a[2] = "body_delta_elite_assault_ba";
	a[3] = "body_delta_elite_assault_bb";
	return a;
}
