// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\mw3_delta_bodies::main());
	codescripts\character::attachFromArray(xmodelalias\mw3_delta_heads::main());
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\mw3_delta_bodies::main());
	codescripts\character::precacheModelArray(xmodelalias\mw3_delta_heads::main());
}
