// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\survival_shotgun_bodies::main());
	codescripts\character::attachFromArray(xmodelalias\survival_shotgun_heads::main());
	self.voice = "russian";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\survival_shotgun_bodies::main());
	codescripts\character::precacheModelArray(xmodelalias\survival_shotgun_heads::main());
}
